# Generated by Django 5.2.5 on 2025-08-17 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile'),
        ('shop', '0004_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(limit_choices_to={'user_id': models.F('user_id')}, on_delete=django.db.models.deletion.PROTECT, to='main.address'),
        ),
    ]
