# Generated by Django 5.2.5 on 2025-08-07 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Starters', 'Starters'), ('Main Course', 'Main Course'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks')], default='Starters', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='main.category'),
        ),
    ]
