# Generated by Django 5.2.5 on 2025-08-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('reservation_date', models.DateTimeField()),
                ('number_of_guests', models.PositiveIntegerField()),
            ],
        ),
    ]
