# Generated by Django 5.2.5 on 2025-08-24 18:21

import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issued_by', models.CharField(max_length=255)),
                ('date_issued', models.DateField()),
                ('credential_id', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issued_by', models.CharField(max_length=255, null=True)),
                ('date_issued', models.DateField(null=True)),
                ('credential_id', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_url', models.URLField(blank=True, max_length=255, null=True)),
                ('certificates', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='certificate_groups', to='maincvapp.certificates')),
            ],
        ),
        migrations.AddField(
            model_name='certificates',
            name='skills',
            field=models.ManyToManyField(related_name='certificates', to='maincvapp.skills'),
        ),
    ]
