# Generated by Django 5.2.5 on 2025-09-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='category',
            field=models.CharField(blank=True, choices=[('programming_languages', 'Programming Languages'), ('frameworks_libraries', 'Frameworks & Libraries'), ('databases', 'Databases'), ('tools', 'Tools'), ('design_prototyping', 'Design & Prototyping')], max_length=50, null=True),
        ),
    ]
